name: ${PACKAGE_NAME}

services:

  work:
    build:
      context: ./.docker
      dockerfile: ./work/Dockerfile
      args:
        ros_distro: ${ROS_DISTRO}
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /home/ubuntu/ros_ws/src
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/ubuntu/ros_ws/src/pkg:rw
    environment:
      TERM: xterm-color
      DISPLAY:
      ROS_DOMAIN_ID:
      RCUTILS_COLORIZED_OUTPUT:
    post_start:
      - command: |
          chown -R ${USER_ID}:${GROUP_ID} /home/ubuntu
        user: root
      - command: |
          sudo apt update && \
          rosdep update && \
          rosdep install -i --from-paths pkg -y; \
        user: ubuntu
        working_dir: /home/ubuntu/ros_ws/src
    restart: always
    ipc: host
    privileged: true
    networks:
      - ros
    tty: true

networks:
  ros:
    driver: bridge