name: ${PACKAGE_NAME}

services:

  work:
    build:
      context: ./.docker
      dockerfile: ./work/Dockerfile
      args:
        ros_distro: ${ROS_DISTRO}
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /home/ubuntu/ros_ws/src/pkg
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/ubuntu/ros_ws/src/pkg:rw
    environment:
      TERM: xterm-color
      DISPLAY:
      ROS_DOMAIN_ID:
      RCUTILS_COLORIZED_OUTPUT:
    restart: always
    ipc: host
    privileged: true
    networks:
      - ros
    tty: true

networks:
  ros:
    driver: bridge